
#include <XdevLKeyboard/XdevLScanCode.h>

namespace xdl {


	static const int xfree86_scancode_table[] = {
		/*  0 */    XDEVL_SCANCODE_UNKNOWN,
		/*  1 */    XDEVL_SCANCODE_ESCAPE,
		/*  2 */    XDEVL_SCANCODE_1,
		/*  3 */    XDEVL_SCANCODE_2,
		/*  4 */    XDEVL_SCANCODE_3,
		/*  5 */    XDEVL_SCANCODE_4,
		/*  6 */    XDEVL_SCANCODE_5,
		/*  7 */    XDEVL_SCANCODE_6,
		/*  8 */    XDEVL_SCANCODE_7,
		/*  9 */    XDEVL_SCANCODE_8,
		/*  10 */   XDEVL_SCANCODE_9,
		/*  11 */   XDEVL_SCANCODE_0,
		/*  12 */   XDEVL_SCANCODE_MINUS,
		/*  13 */   XDEVL_SCANCODE_EQUALS,
		/*  14 */   XDEVL_SCANCODE_BACKSPACE,
		/*  15 */   XDEVL_SCANCODE_TAB,
		/*  16 */   XDEVL_SCANCODE_Q,
		/*  17 */   XDEVL_SCANCODE_W,
		/*  18 */   XDEVL_SCANCODE_E,
		/*  19 */   XDEVL_SCANCODE_R,
		/*  20 */   XDEVL_SCANCODE_T,
		/*  21 */   XDEVL_SCANCODE_Y,
		/*  22 */   XDEVL_SCANCODE_U,
		/*  23 */   XDEVL_SCANCODE_I,
		/*  24 */   XDEVL_SCANCODE_O,
		/*  25 */   XDEVL_SCANCODE_P,
		/*  26 */   XDEVL_SCANCODE_LEFTBRACKET,
		/*  27 */   XDEVL_SCANCODE_RIGHTBRACKET,
		/*  28 */   XDEVL_SCANCODE_RETURN,
		/*  29 */   XDEVL_SCANCODE_LCTRL,
		/*  30 */   XDEVL_SCANCODE_A,
		/*  31 */   XDEVL_SCANCODE_S,
		/*  32 */   XDEVL_SCANCODE_D,
		/*  33 */   XDEVL_SCANCODE_F,
		/*  34 */   XDEVL_SCANCODE_G,
		/*  35 */   XDEVL_SCANCODE_H,
		/*  36 */   XDEVL_SCANCODE_J,
		/*  37 */   XDEVL_SCANCODE_K,
		/*  38 */   XDEVL_SCANCODE_L,
		/*  39 */   XDEVL_SCANCODE_SEMICOLON,
		/*  40 */   XDEVL_SCANCODE_APOSTROPHE,
		/*  41 */   XDEVL_SCANCODE_GRAVE,
		/*  42 */   XDEVL_SCANCODE_LSHIFT,
		/*  43 */   XDEVL_SCANCODE_BACKSLASH,
		/*  44 */   XDEVL_SCANCODE_Z,
		/*  45 */   XDEVL_SCANCODE_X,
		/*  46 */   XDEVL_SCANCODE_C,
		/*  47 */   XDEVL_SCANCODE_V,
		/*  48 */   XDEVL_SCANCODE_B,
		/*  49 */   XDEVL_SCANCODE_N,
		/*  50 */   XDEVL_SCANCODE_M,
		/*  51 */   XDEVL_SCANCODE_COMMA,
		/*  52 */   XDEVL_SCANCODE_PERIOD,
		/*  53 */   XDEVL_SCANCODE_SLASH,
		/*  54 */   XDEVL_SCANCODE_RSHIFT,
		/*  55 */   XDEVL_SCANCODE_KP_MULTIPLY,
		/*  56 */   XDEVL_SCANCODE_LALT,
		/*  57 */   XDEVL_SCANCODE_SPACE,
		/*  58 */   XDEVL_SCANCODE_CAPSLOCK,
		/*  59 */   XDEVL_SCANCODE_F1,
		/*  60 */   XDEVL_SCANCODE_F2,
		/*  61 */   XDEVL_SCANCODE_F3,
		/*  62 */   XDEVL_SCANCODE_F4,
		/*  63 */   XDEVL_SCANCODE_F5,
		/*  64 */   XDEVL_SCANCODE_F6,
		/*  65 */   XDEVL_SCANCODE_F7,
		/*  66 */   XDEVL_SCANCODE_F8,
		/*  67 */   XDEVL_SCANCODE_F9,
		/*  68 */   XDEVL_SCANCODE_F10,
		/*  69 */   XDEVL_SCANCODE_NUMLOCKCLEAR,
		/*  70 */   XDEVL_SCANCODE_SCROLLLOCK,
		/*  71 */   XDEVL_SCANCODE_KP_7,
		/*  72 */   XDEVL_SCANCODE_KP_8,
		/*  73 */   XDEVL_SCANCODE_KP_9,
		/*  74 */   XDEVL_SCANCODE_KP_MINUS,
		/*  75 */   XDEVL_SCANCODE_KP_4,
		/*  76 */   XDEVL_SCANCODE_KP_5,
		/*  77 */   XDEVL_SCANCODE_KP_6,
		/*  78 */   XDEVL_SCANCODE_KP_PLUS,
		/*  79 */   XDEVL_SCANCODE_KP_1,
		/*  80 */   XDEVL_SCANCODE_KP_2,
		/*  81 */   XDEVL_SCANCODE_KP_3,
		/*  82 */   XDEVL_SCANCODE_KP_0,
		/*  83 */   XDEVL_SCANCODE_KP_PERIOD,
		/*  84 */   XDEVL_SCANCODE_SYSREQ,
		/*  85 */   XDEVL_SCANCODE_MODE,
		/*  86 */   XDEVL_SCANCODE_NONUSBACKSLASH,
		/*  87 */   XDEVL_SCANCODE_F11,
		/*  88 */   XDEVL_SCANCODE_F12,
		/*  89 */   XDEVL_SCANCODE_HOME,
		/*  90 */   XDEVL_SCANCODE_UP,
		/*  91 */   XDEVL_SCANCODE_PAGEUP,
		/*  92 */   XDEVL_SCANCODE_LEFT,
		/*  93 */   XDEVL_SCANCODE_BRIGHTNESSDOWN, /* on PowerBook G4 / KEY_Begin */
		/*  94 */   XDEVL_SCANCODE_RIGHT,
		/*  95 */   XDEVL_SCANCODE_END,
		/*  96 */   XDEVL_SCANCODE_DOWN,
		/*  97 */   XDEVL_SCANCODE_PAGEDOWN,
		/*  98 */   XDEVL_SCANCODE_INSERT,
		/*  99 */   XDEVL_SCANCODE_DELETE,
		/*  100 */  XDEVL_SCANCODE_KP_ENTER,
		/*  101 */  XDEVL_SCANCODE_RCTRL,
		/*  102 */  XDEVL_SCANCODE_PAUSE,
		/*  103 */  XDEVL_SCANCODE_PRINTSCREEN,
		/*  104 */  XDEVL_SCANCODE_KP_DIVIDE,
		/*  105 */  XDEVL_SCANCODE_RALT,
		/*  106 */  XDEVL_SCANCODE_UNKNOWN, /* BREAK */
		/*  107 */  XDEVL_SCANCODE_LGUI,
		/*  108 */  XDEVL_SCANCODE_RGUI,
		/*  109 */  XDEVL_SCANCODE_APPLICATION,
		/*  110 */  XDEVL_SCANCODE_F13,
		/*  111 */  XDEVL_SCANCODE_F14,
		/*  112 */  XDEVL_SCANCODE_F15,
		/*  113 */  XDEVL_SCANCODE_F16,
		/*  114 */  XDEVL_SCANCODE_F17,
		/*  115 */  XDEVL_SCANCODE_UNKNOWN,
		/*  116 */  XDEVL_SCANCODE_UNKNOWN, /* is translated to XK_ISO_Level3_Shift by my X server, but I have no keyboard that generates this code, so I don't know what the correct XDEVL_SCANCODE_* for it is */
		/*  117 */  XDEVL_SCANCODE_UNKNOWN,
		/*  118 */  XDEVL_SCANCODE_KP_EQUALS,
		/*  119 */  XDEVL_SCANCODE_UNKNOWN,
		/*  120 */  XDEVL_SCANCODE_UNKNOWN,
		/*  121 */  XDEVL_SCANCODE_UNKNOWN,
		/*  122 */  XDEVL_SCANCODE_UNKNOWN,
		/*  123 */  XDEVL_SCANCODE_UNKNOWN,
		/*  124 */  XDEVL_SCANCODE_UNKNOWN,
		/*  125 */  XDEVL_SCANCODE_INTERNATIONAL3, /* Yen */
		/*  126 */  XDEVL_SCANCODE_UNKNOWN,
		/*  127 */  XDEVL_SCANCODE_UNKNOWN,
		/*  128 */  XDEVL_SCANCODE_UNKNOWN,
		/*  129 */  XDEVL_SCANCODE_UNKNOWN,
		/*  130 */  XDEVL_SCANCODE_UNKNOWN,
		/*  131 */  XDEVL_SCANCODE_UNKNOWN,
		/*  132 */  XDEVL_SCANCODE_POWER,
		/*  133 */  XDEVL_SCANCODE_MUTE,
		/*  134 */  XDEVL_SCANCODE_VOLUMEDOWN,
		/*  135 */  XDEVL_SCANCODE_VOLUMEUP,
		/*  136 */  XDEVL_SCANCODE_HELP,
		/*  137 */  XDEVL_SCANCODE_STOP,
		/*  138 */  XDEVL_SCANCODE_AGAIN,
		/*  139 */  XDEVL_SCANCODE_UNKNOWN, /* PROPS */
		/*  140 */  XDEVL_SCANCODE_UNDO,
		/*  141 */  XDEVL_SCANCODE_UNKNOWN, /* FRONT */
		/*  142 */  XDEVL_SCANCODE_COPY,
		/*  143 */  XDEVL_SCANCODE_UNKNOWN, /* OPEN */
		/*  144 */  XDEVL_SCANCODE_PASTE,
		/*  145 */  XDEVL_SCANCODE_FIND,
		/*  146 */  XDEVL_SCANCODE_CUT,
	};

	/* for wireless usb keyboard (manufacturer TRUST) without numpad. */
	static const int xfree86_scancode_table2[] = {
		/*  0 */    XDEVL_SCANCODE_UNKNOWN,
		/*  1 */    XDEVL_SCANCODE_ESCAPE,
		/*  2 */    XDEVL_SCANCODE_1,
		/*  3 */    XDEVL_SCANCODE_2,
		/*  4 */    XDEVL_SCANCODE_3,
		/*  5 */    XDEVL_SCANCODE_4,
		/*  6 */    XDEVL_SCANCODE_5,
		/*  7 */    XDEVL_SCANCODE_6,
		/*  8 */    XDEVL_SCANCODE_7,
		/*  9 */    XDEVL_SCANCODE_8,
		/*  10 */   XDEVL_SCANCODE_9,
		/*  11 */   XDEVL_SCANCODE_0,
		/*  12 */   XDEVL_SCANCODE_MINUS,
		/*  13 */   XDEVL_SCANCODE_EQUALS,
		/*  14 */   XDEVL_SCANCODE_BACKSPACE,
		/*  15 */   XDEVL_SCANCODE_TAB,
		/*  16 */   XDEVL_SCANCODE_Q,
		/*  17 */   XDEVL_SCANCODE_W,
		/*  18 */   XDEVL_SCANCODE_E,
		/*  19 */   XDEVL_SCANCODE_R,
		/*  20 */   XDEVL_SCANCODE_T,
		/*  21 */   XDEVL_SCANCODE_Y,
		/*  22 */   XDEVL_SCANCODE_U,
		/*  23 */   XDEVL_SCANCODE_I,
		/*  24 */   XDEVL_SCANCODE_O,
		/*  25 */   XDEVL_SCANCODE_P,
		/*  26 */   XDEVL_SCANCODE_LEFTBRACKET,
		/*  27 */   XDEVL_SCANCODE_RIGHTBRACKET,
		/*  28 */   XDEVL_SCANCODE_RETURN,
		/*  29 */   XDEVL_SCANCODE_LCTRL,
		/*  30 */   XDEVL_SCANCODE_A,
		/*  31 */   XDEVL_SCANCODE_S,
		/*  32 */   XDEVL_SCANCODE_D,
		/*  33 */   XDEVL_SCANCODE_F,
		/*  34 */   XDEVL_SCANCODE_G,
		/*  35 */   XDEVL_SCANCODE_H,
		/*  36 */   XDEVL_SCANCODE_J,
		/*  37 */   XDEVL_SCANCODE_K,
		/*  38 */   XDEVL_SCANCODE_L,
		/*  39 */   XDEVL_SCANCODE_SEMICOLON,
		/*  40 */   XDEVL_SCANCODE_APOSTROPHE,
		/*  41 */   XDEVL_SCANCODE_GRAVE,
		/*  42 */   XDEVL_SCANCODE_LSHIFT,
		/*  43 */   XDEVL_SCANCODE_BACKSLASH,
		/*  44 */   XDEVL_SCANCODE_Z,
		/*  45 */   XDEVL_SCANCODE_X,
		/*  46 */   XDEVL_SCANCODE_C,
		/*  47 */   XDEVL_SCANCODE_V,
		/*  48 */   XDEVL_SCANCODE_B,
		/*  49 */   XDEVL_SCANCODE_N,
		/*  50 */   XDEVL_SCANCODE_M,
		/*  51 */   XDEVL_SCANCODE_COMMA,
		/*  52 */   XDEVL_SCANCODE_PERIOD,
		/*  53 */   XDEVL_SCANCODE_SLASH,
		/*  54 */   XDEVL_SCANCODE_RSHIFT,
		/*  55 */   XDEVL_SCANCODE_KP_MULTIPLY,
		/*  56 */   XDEVL_SCANCODE_LALT,
		/*  57 */   XDEVL_SCANCODE_SPACE,
		/*  58 */   XDEVL_SCANCODE_CAPSLOCK,
		/*  59 */   XDEVL_SCANCODE_F1,
		/*  60 */   XDEVL_SCANCODE_F2,
		/*  61 */   XDEVL_SCANCODE_F3,
		/*  62 */   XDEVL_SCANCODE_F4,
		/*  63 */   XDEVL_SCANCODE_F5,
		/*  64 */   XDEVL_SCANCODE_F6,
		/*  65 */   XDEVL_SCANCODE_F7,
		/*  66 */   XDEVL_SCANCODE_F8,
		/*  67 */   XDEVL_SCANCODE_F9,
		/*  68 */   XDEVL_SCANCODE_F10,
		/*  69 */   XDEVL_SCANCODE_NUMLOCKCLEAR,
		/*  70 */   XDEVL_SCANCODE_SCROLLLOCK,
		/*  71 */   XDEVL_SCANCODE_KP_7,
		/*  72 */   XDEVL_SCANCODE_KP_8,
		/*  73 */   XDEVL_SCANCODE_KP_9,
		/*  74 */   XDEVL_SCANCODE_KP_MINUS,
		/*  75 */   XDEVL_SCANCODE_KP_4,
		/*  76 */   XDEVL_SCANCODE_KP_5,
		/*  77 */   XDEVL_SCANCODE_KP_6,
		/*  78 */   XDEVL_SCANCODE_KP_PLUS,
		/*  79 */   XDEVL_SCANCODE_KP_1,
		/*  80 */   XDEVL_SCANCODE_KP_2,
		/*  81 */   XDEVL_SCANCODE_KP_3,
		/*  82 */   XDEVL_SCANCODE_KP_0,
		/*  83 */   XDEVL_SCANCODE_KP_PERIOD,
		/*  84 */   XDEVL_SCANCODE_SYSREQ,    /* ???? */
		/*  85 */   XDEVL_SCANCODE_MODE,      /* ???? */
		/*  86 */   XDEVL_SCANCODE_NONUSBACKSLASH,
		/*  87 */   XDEVL_SCANCODE_F11,
		/*  88 */   XDEVL_SCANCODE_F12,
		/*  89 */   XDEVL_SCANCODE_UNKNOWN,
		/*  90 */   XDEVL_SCANCODE_UNKNOWN,   /* Katakana */
		/*  91 */   XDEVL_SCANCODE_UNKNOWN,   /* Hiragana */
		/*  92 */   XDEVL_SCANCODE_UNKNOWN,   /* Henkan_Mode */
		/*  93 */   XDEVL_SCANCODE_UNKNOWN,   /* Hiragana_Katakana */
		/*  94 */   XDEVL_SCANCODE_UNKNOWN,   /* Muhenkan */
		/*  95 */   XDEVL_SCANCODE_UNKNOWN,
		/*  96 */   XDEVL_SCANCODE_KP_ENTER,
		/*  97 */   XDEVL_SCANCODE_RCTRL,
		/*  98 */   XDEVL_SCANCODE_KP_DIVIDE,
		/*  99 */   XDEVL_SCANCODE_PRINTSCREEN,
		/* 100 */   XDEVL_SCANCODE_RALT,      /* ISO_Level3_Shift, ALTGR, RALT */
		/* 101 */   XDEVL_SCANCODE_UNKNOWN,   /* Linefeed */
		/* 102 */   XDEVL_SCANCODE_HOME,
		/* 103 */   XDEVL_SCANCODE_UP,
		/* 104 */   XDEVL_SCANCODE_PAGEUP,
		/* 105 */   XDEVL_SCANCODE_LEFT,
		/* 106 */   XDEVL_SCANCODE_RIGHT,
		/* 107 */   XDEVL_SCANCODE_END,
		/* 108 */   XDEVL_SCANCODE_DOWN,
		/* 109 */   XDEVL_SCANCODE_PAGEDOWN,
		/* 110 */   XDEVL_SCANCODE_INSERT,
		/* 111 */   XDEVL_SCANCODE_DELETE,
		/* 112 */   XDEVL_SCANCODE_UNKNOWN,
		/* 113 */   XDEVL_SCANCODE_MUTE,
		/* 114 */   XDEVL_SCANCODE_VOLUMEDOWN,
		/* 115 */   XDEVL_SCANCODE_VOLUMEUP,
		/* 116 */   XDEVL_SCANCODE_POWER,
		/* 117 */   XDEVL_SCANCODE_KP_EQUALS,
		/* 118 */   XDEVL_SCANCODE_UNKNOWN,   /* plusminus */
		/* 119 */   XDEVL_SCANCODE_PAUSE,
		/* 120 */   XDEVL_SCANCODE_UNKNOWN,   /* XF86LaunchA */
		/* 121 */   XDEVL_SCANCODE_UNKNOWN,   /* KP_Decimal */
		/* 122 */   XDEVL_SCANCODE_UNKNOWN,   /* Hangul */
		/* 123 */   XDEVL_SCANCODE_UNKNOWN,   /* Hangul_Hanja */
		/* 124 */   XDEVL_SCANCODE_UNKNOWN,
		/* 125 */   XDEVL_SCANCODE_LGUI,
		/* 126 */   XDEVL_SCANCODE_RGUI,
		/* 127 */   XDEVL_SCANCODE_APPLICATION,
		/* 128 */   XDEVL_SCANCODE_CANCEL,
		/* 129 */   XDEVL_SCANCODE_AGAIN,
		/* 130 */   XDEVL_SCANCODE_UNKNOWN,   /* SunProps */
		/* 131 */   XDEVL_SCANCODE_UNDO,
		/* 132 */   XDEVL_SCANCODE_UNKNOWN,   /* SunFront */
		/* 133 */   XDEVL_SCANCODE_COPY,
		/* 134 */   XDEVL_SCANCODE_UNKNOWN,   /* SunOpen */
		/* 135 */   XDEVL_SCANCODE_PASTE,
		/* 136 */   XDEVL_SCANCODE_FIND,
		/* 137 */   XDEVL_SCANCODE_CUT,
		/* 138 */   XDEVL_SCANCODE_HELP,
		/* 139 */   XDEVL_SCANCODE_UNKNOWN,   /* XF86MenuKB */
		/* 140 */   XDEVL_SCANCODE_CALCULATOR,
		/* 141 */   XDEVL_SCANCODE_UNKNOWN,
		/* 142 */   XDEVL_SCANCODE_SLEEP,
		/* 143 */   XDEVL_SCANCODE_UNKNOWN,   /* XF86WakeUp */
		/* 144 */   XDEVL_SCANCODE_UNKNOWN,   /* XF86Explorer */
		/* 145 */   XDEVL_SCANCODE_UNKNOWN,   /* XF86Send */
		/* 146 */   XDEVL_SCANCODE_UNKNOWN,
		/* 147 */   XDEVL_SCANCODE_UNKNOWN,   /* XF86Xfer */
		/* 148 */   XDEVL_SCANCODE_APP1,      /* XF86Launch1 */
		/* 149 */   XDEVL_SCANCODE_APP2,      /* XF86Launch2 */
		/* 150 */   XDEVL_SCANCODE_WWW,
		/* 151 */   XDEVL_SCANCODE_UNKNOWN,   /* XF86DOS */
		/* 152 */   XDEVL_SCANCODE_UNKNOWN,   /* XF86ScreenSaver */
		/* 153 */   XDEVL_SCANCODE_UNKNOWN,
		/* 154 */   XDEVL_SCANCODE_UNKNOWN,   /* XF86RotateWindows */
		/* 155 */   XDEVL_SCANCODE_MAIL,
		/* 156 */   XDEVL_SCANCODE_AC_BOOKMARKS,   /* XF86Favorites */
		/* 157 */   XDEVL_SCANCODE_COMPUTER,
		/* 158 */   XDEVL_SCANCODE_AC_BACK,
		/* 159 */   XDEVL_SCANCODE_AC_FORWARD,
		/* 160 */   XDEVL_SCANCODE_UNKNOWN,
		/* 161 */   XDEVL_SCANCODE_EJECT,
		/* 162 */   XDEVL_SCANCODE_EJECT,
		/* 163 */   XDEVL_SCANCODE_AUDIONEXT,
		/* 164 */   XDEVL_SCANCODE_AUDIOPLAY,
		/* 165 */   XDEVL_SCANCODE_AUDIOPREV,
		/* 166 */   XDEVL_SCANCODE_AUDIOSTOP,
		/* 167 */   XDEVL_SCANCODE_UNKNOWN,   /* XF86AudioRecord */
		/* 168 */   XDEVL_SCANCODE_UNKNOWN,   /* XF86AudioRewind */
		/* 169 */   XDEVL_SCANCODE_UNKNOWN,   /* XF86Phone */
		/* 170 */   XDEVL_SCANCODE_UNKNOWN,
		/* 171 */   XDEVL_SCANCODE_F13,       /* XF86Tools */
		/* 172 */   XDEVL_SCANCODE_AC_HOME,
		/* 173 */   XDEVL_SCANCODE_AC_REFRESH,
		/* 174 */   XDEVL_SCANCODE_UNKNOWN,   /* XF86Close */
		/* 175 */   XDEVL_SCANCODE_UNKNOWN,
		/* 176 */   XDEVL_SCANCODE_UNKNOWN,
		/* 177 */   XDEVL_SCANCODE_UNKNOWN,   /* XF86ScrollUp */
		/* 178 */   XDEVL_SCANCODE_UNKNOWN,   /* XF86ScrollDown */
		/* 179 */   XDEVL_SCANCODE_UNKNOWN,   /* parenleft */
		/* 180 */   XDEVL_SCANCODE_UNKNOWN,   /* parenright */
		/* 181 */   XDEVL_SCANCODE_UNKNOWN,   /* XF86New */
		/* 182 */   XDEVL_SCANCODE_AGAIN,
		/* 183 */   XDEVL_SCANCODE_F13,       /* XF86Tools */
		/* 184 */   XDEVL_SCANCODE_F14,       /* XF86Launch5 */
		/* 185 */   XDEVL_SCANCODE_F15,       /* XF86Launch6 */
		/* 186 */   XDEVL_SCANCODE_F16,       /* XF86Launch7 */
		/* 187 */   XDEVL_SCANCODE_F17,       /* XF86Launch8 */
		/* 188 */   XDEVL_SCANCODE_F18,       /* XF86Launch9 */
		/* 189 */   XDEVL_SCANCODE_F19,       /* null keysym */
		/* 190 */   XDEVL_SCANCODE_UNKNOWN,
		/* 191 */   XDEVL_SCANCODE_UNKNOWN,
		/* 192 */   XDEVL_SCANCODE_UNKNOWN,   /* XF86TouchpadToggle */
		/* 193 */   XDEVL_SCANCODE_UNKNOWN,
		/* 194 */   XDEVL_SCANCODE_UNKNOWN,
		/* 195 */   XDEVL_SCANCODE_MODE,
		/* 196 */   XDEVL_SCANCODE_UNKNOWN,
		/* 197 */   XDEVL_SCANCODE_UNKNOWN,
		/* 198 */   XDEVL_SCANCODE_UNKNOWN,
		/* 199 */   XDEVL_SCANCODE_UNKNOWN,
		/* 200 */   XDEVL_SCANCODE_AUDIOPLAY,
		/* 201 */   XDEVL_SCANCODE_UNKNOWN,   /* XF86AudioPause */
		/* 202 */   XDEVL_SCANCODE_UNKNOWN,   /* XF86Launch3 */
		/* 203 */   XDEVL_SCANCODE_UNKNOWN,   /* XF86Launch4 */
		/* 204 */   XDEVL_SCANCODE_UNKNOWN,   /* XF86LaunchB */
		/* 205 */   XDEVL_SCANCODE_UNKNOWN,   /* XF86Suspend */
		/* 206 */   XDEVL_SCANCODE_UNKNOWN,   /* XF86Close */
		/* 207 */   XDEVL_SCANCODE_AUDIOPLAY,
		/* 208 */   XDEVL_SCANCODE_AUDIONEXT,
		/* 209 */   XDEVL_SCANCODE_UNKNOWN,
		/* 210 */   XDEVL_SCANCODE_PRINTSCREEN,
		/* 211 */   XDEVL_SCANCODE_UNKNOWN,
		/* 212 */   XDEVL_SCANCODE_UNKNOWN,   /* XF86WebCam */
		/* 213 */   XDEVL_SCANCODE_UNKNOWN,
		/* 214 */   XDEVL_SCANCODE_UNKNOWN,
		/* 215 */   XDEVL_SCANCODE_MAIL,
		/* 216 */   XDEVL_SCANCODE_UNKNOWN,
		/* 217 */   XDEVL_SCANCODE_AC_SEARCH,
		/* 218 */   XDEVL_SCANCODE_UNKNOWN,
		/* 219 */   XDEVL_SCANCODE_UNKNOWN,   /* XF86Finance */
		/* 220 */   XDEVL_SCANCODE_UNKNOWN,
		/* 221 */   XDEVL_SCANCODE_UNKNOWN,   /* XF86Shop */
		/* 222 */   XDEVL_SCANCODE_UNKNOWN,
		/* 223 */   XDEVL_SCANCODE_STOP,
		/* 224 */   XDEVL_SCANCODE_BRIGHTNESSDOWN,
		/* 225 */   XDEVL_SCANCODE_BRIGHTNESSUP,
		/* 226 */   XDEVL_SCANCODE_MEDIASELECT,
		/* 227 */   XDEVL_SCANCODE_DISPLAYSWITCH,
		/* 228 */   XDEVL_SCANCODE_KBDILLUMTOGGLE,
		/* 229 */   XDEVL_SCANCODE_KBDILLUMDOWN,
		/* 230 */   XDEVL_SCANCODE_KBDILLUMUP,
		/* 231 */   XDEVL_SCANCODE_UNKNOWN,   /* XF86Send */
		/* 232 */   XDEVL_SCANCODE_UNKNOWN,   /* XF86Reply */
		/* 233 */   XDEVL_SCANCODE_UNKNOWN,   /* XF86MailForward */
		/* 234 */   XDEVL_SCANCODE_UNKNOWN,   /* XF86Save */
		/* 235 */   XDEVL_SCANCODE_UNKNOWN,   /* XF86Documents */
		/* 236 */   XDEVL_SCANCODE_UNKNOWN,   /* XF86Battery */
		/* 237 */   XDEVL_SCANCODE_UNKNOWN,   /* XF86Bluetooth */
		/* 238 */   XDEVL_SCANCODE_UNKNOWN,   /* XF86WLAN */
	};
}
/* *INDENT-ON* */
